/* eslint-disable import/prefer-default-export */

/* *~~*~~*~~*~~*~~* NAVBAR REDUCER *~~*~~*~~*~~*~~* */
export const NAVBAR_GET_REQUEST = 'NAVBAR_GET_REQUEST';
export const NAVBAR_GET_SUCCESS = 'NAVBAR_GET_SUCCESS';
export const NAVBAR_GET_FAILURE = 'NAVBAR_GET_FAILURE';

/* *~~*~~*~~*~~*~~* PROJECTS HISTORY REDUCER *~~*~~*~~*~~*~~* */
export const PROJECTS_HISTORY_GET_REQUEST = 'PROJECTS_HISTORY_GET_REQUEST';
export const PROJECTS_HISTORY_GET_SUCCESS = 'PROJECTS_HISTORY_GET_SUCCESS';
export const PROJECTS_HISTORY_GET_FAILURE = 'PROJECTS_HISTORY_GET_FAILURE';

/* *~~*~~*~~*~~*~~* ACTIVE PARTICIPANTS REDUCER *~~*~~*~~*~~*~~* */
export const ACTIVE_PARTICIPANTS_GET_REQUEST = 'ACTIVE_PARTICIPANTS_GET_REQUEST';
export const ACTIVE_PARTICIPANTS_GET_SUCCESS = 'ACTIVE_PARTICIPANTS_GET_SUCCESS';
export const ACTIVE_PARTICIPANTS_GET_FAILURE = 'ACTIVE_PARTICIPANTS_GET_FAILURE';

/* *~~*~~*~~*~~*~~* CURRENT PROJECT REDUCER *~~*~~*~~*~~*~~* */
export const CURRENT_PROJECT_GET_REQUEST = 'CURRENT_PROJECT_GET_REQUEST';
export const CURRENT_PROJECT_GET_SUCCESS = 'CURRENT_PROJECT_GET_SUCCESS';
export const CURRENT_PROJECT_GET_FAILURE = 'CURRENT_PROJECT_GET_FAILURE';

/* *~~*~~*~~*~~*~~* JOIN PROJECT REDUCER *~~*~~*~~*~~*~~* */

export const JOIN_PROJECT_GET_REQUEST = 'JOIN_PROJECT_GET_REQUEST';
export const JOIN_PROJECT_GET_SUCCESS = 'JOIN_PROJECT_GET_SUCCESS';
export const JOIN_PROJECT_GET_FAILURE = 'JOIN_PROJECT_GET_FAILURE';

/* *~~*~~*~~*~~*~~* MODAL REDUCER *~~*~~*~~*~~*~~* */

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SET_ANIMATION = 'SET_ANIMATION';
